// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1O2e6zP3vWPVnyqVdw7zcGAaDU307o0k',
    appId: '1:438831102397:web:f8900cd66a64e67044bad4',
    messagingSenderId: '438831102397',
    projectId: 'safespace-5fa0d',
    authDomain: 'safespace-5fa0d.firebaseapp.com',
    storageBucket: 'safespace-5fa0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1R6FYyGaueN6LnRELThZP5lffXiiAVPM',
    appId: '1:438831102397:android:687edc7a3214362b44bad4',
    messagingSenderId: '438831102397',
    projectId: 'safespace-5fa0d',
    storageBucket: 'safespace-5fa0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8u6IKAENaHB0032bZCMcGt_7RDxT4bWs',
    appId: '1:438831102397:ios:66a4e6fec122933544bad4',
    messagingSenderId: '438831102397',
    projectId: 'safespace-5fa0d',
    storageBucket: 'safespace-5fa0d.firebasestorage.app',
    iosBundleId: 'com.shubhampandya.safeSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1O2e6zP3vWPVnyqVdw7zcGAaDU307o0k',
    appId: '1:438831102397:web:9134a2798e35183344bad4',
    messagingSenderId: '438831102397',
    projectId: 'safespace-5fa0d',
    authDomain: 'safespace-5fa0d.firebaseapp.com',
    storageBucket: 'safespace-5fa0d.firebasestorage.app',
  );
}
